name: 'Electron Release'
on:
  workflow_dispatch:
    inputs:
      chosen-os:
        required: true
        type: choice
        options:
        - Windows
        - Ubuntu
        - macOS

jobs:
  test:
    runs-on: ["${{ inputs.chosen-os }}"]
    steps:
    - run: echo Hello world!
    - name: version
      run: echo "::set-output name=version::'1.0.0'"
      id: version
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}
