name: 'Electron Release'
on:
  workflow_dispatch:
    inputs:
      chosen-os:
        required: true
        type: choice
        options:
        - Windows
        - Ubuntu
        - macOS

jobs:
  build_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 21.3.0
    - name: install dependencies
      working-directory: ./Electron
      run: npm install
    - name: build
      working-directory: ./Electron
      run: npm run package